"""Curated drug catalogue for the demo seeder (app.seed_demo).

Real medicines and CIS/import manufacturers, Russian labels, Tajik-pharmacy
assortment. Each base drug expands into one master_catalog row per variant
(dosage × pack), so ~80 base drugs → ~190 master rows.

Fields per base drug:
  brand        — торговое название (brand_name)
  inn          — МНН (международное непатентованное наименование)
  manufacturer — производитель
  form         — лекарственная форма
  atx          — код АТХ
  dispensing   — 'otc' | 'prescription' | 'special'
  storage      — 'normal' | 'cold' | 'frozen'
  category     — раздел витрины (русский)
  variants     — list of (dosage, pack_size, retail_price_tjs)

retail_price_tjs is the shelf price in сомони (TJS), as a plain string fed into
Decimal — no floats anywhere.
"""

from __future__ import annotations

from typing import TypedDict


class DrugDef(TypedDict):
    brand: str
    inn: str
    manufacturer: str
    form: str
    atx: str
    dispensing: str  # 'otc' | 'prescription' | 'special'
    storage: str  # 'normal' | 'cold' | 'frozen'
    category: str
    variants: list[tuple[str, str, str]]  # (dosage, pack_size, retail_price_tjs)


DRUGS: list[DrugDef] = [
    # ── Анальгетики и НПВС ────────────────────────────────────────────────
    {
        "brand": "Парацетамол",
        "inn": "Парацетамол",
        "manufacturer": "Фармстандарт",
        "form": "таблетки",
        "atx": "N02BE01",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Анальгетики и НПВС",
        "variants": [("500 мг", "№10", "3.50"), ("500 мг", "№20", "6.20")],
    },
    {
        "brand": "Анальгин",
        "inn": "Метамизол натрия",
        "manufacturer": "Фармстандарт",
        "form": "таблетки",
        "atx": "N02BB02",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Анальгетики и НПВС",
        "variants": [("500 мг", "№10", "4.00")],
    },
    {
        "brand": "Ибупрофен",
        "inn": "Ибупрофен",
        "manufacturer": "Борисовский ЗМП",
        "form": "таблетки покрытые",
        "atx": "M01AE01",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Анальгетики и НПВС",
        "variants": [("200 мг", "№20", "9.00"), ("400 мг", "№20", "14.50")],
    },
    {
        "brand": "Нурофен",
        "inn": "Ибупрофен",
        "manufacturer": "Reckitt Benckiser",
        "form": "таблетки покрытые",
        "atx": "M01AE01",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Анальгетики и НПВС",
        "variants": [("200 мг", "№10", "18.00"), ("400 мг", "№12", "29.00")],
    },
    {
        "brand": "Найз",
        "inn": "Нимесулид",
        "manufacturer": "Dr. Reddy's",
        "form": "таблетки",
        "atx": "M01AX17",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Анальгетики и НПВС",
        "variants": [("100 мг", "№20", "26.00")],
    },
    {
        "brand": "Диклофенак",
        "inn": "Диклофенак",
        "manufacturer": "Hemofarm",
        "form": "раствор для инъекций",
        "atx": "M01AB05",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Анальгетики и НПВС",
        "variants": [("25 мг/мл 3 мл", "№5", "22.00")],
    },
    {
        "brand": "Вольтарен",
        "inn": "Диклофенак",
        "manufacturer": "Novartis",
        "form": "гель",
        "atx": "M02AA15",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Анальгетики и НПВС",
        "variants": [("1% 50 г", "туба", "48.00")],
    },
    {
        "brand": "Кеторол",
        "inn": "Кеторолак",
        "manufacturer": "Dr. Reddy's",
        "form": "таблетки",
        "atx": "M01AB15",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Анальгетики и НПВС",
        "variants": [("10 мг", "№20", "31.00")],
    },
    {
        "brand": "Цитрамон П",
        "inn": "Комбинация",
        "manufacturer": "Фармстандарт",
        "form": "таблетки",
        "atx": "N02BA51",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Анальгетики и НПВС",
        "variants": [("№10", "№10", "4.20")],
    },
    {
        "brand": "Пенталгин",
        "inn": "Комбинация",
        "manufacturer": "Фармстандарт",
        "form": "таблетки",
        "atx": "N02BE51",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Анальгетики и НПВС",
        "variants": [("№12", "№12", "33.00")],
    },
    # ── Спазмолитики ──────────────────────────────────────────────────────
    {
        "brand": "Но-шпа",
        "inn": "Дротаверин",
        "manufacturer": "Gedeon Richter",
        "form": "таблетки",
        "atx": "A03AD02",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Спазмолитики",
        "variants": [("40 мг", "№24", "28.00"), ("40 мг", "№64", "62.00")],
    },
    {
        "brand": "Дротаверин",
        "inn": "Дротаверин",
        "manufacturer": "Озон",
        "form": "таблетки",
        "atx": "A03AD02",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Спазмолитики",
        "variants": [("40 мг", "№20", "9.50")],
    },
    {
        "brand": "Папаверин",
        "inn": "Папаверин",
        "manufacturer": "Биосинтез",
        "form": "суппозитории",
        "atx": "A03AD01",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Спазмолитики",
        "variants": [("20 мг", "№10", "12.00")],
    },
    {
        "brand": "Бускопан",
        "inn": "Гиосцина бутилбромид",
        "manufacturer": "Boehringer Ingelheim",
        "form": "таблетки",
        "atx": "A03BB01",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Спазмолитики",
        "variants": [("10 мг", "№20", "44.00")],
    },
    # ── ЖКТ ───────────────────────────────────────────────────────────────
    {
        "brand": "Омепразол",
        "inn": "Омепразол",
        "manufacturer": "Hemofarm",
        "form": "капсулы",
        "atx": "A02BC01",
        "dispensing": "otc",
        "storage": "normal",
        "category": "ЖКТ",
        "variants": [("20 мг", "№30", "21.00"), ("20 мг", "№14", "12.00")],
    },
    {
        "brand": "Омез",
        "inn": "Омепразол",
        "manufacturer": "Dr. Reddy's",
        "form": "капсулы",
        "atx": "A02BC01",
        "dispensing": "otc",
        "storage": "normal",
        "category": "ЖКТ",
        "variants": [("20 мг", "№30", "39.00")],
    },
    {
        "brand": "Де-Нол",
        "inn": "Висмута трикалия дицитрат",
        "manufacturer": "Astellas",
        "form": "таблетки покрытые",
        "atx": "A02BX05",
        "dispensing": "otc",
        "storage": "normal",
        "category": "ЖКТ",
        "variants": [("120 мг", "№56", "118.00")],
    },
    {
        "brand": "Мезим форте",
        "inn": "Панкреатин",
        "manufacturer": "Berlin-Chemie",
        "form": "таблетки покрытые",
        "atx": "A09AA02",
        "dispensing": "otc",
        "storage": "normal",
        "category": "ЖКТ",
        "variants": [("№20", "№20", "34.00"), ("№80", "№80", "98.00")],
    },
    {
        "brand": "Креон",
        "inn": "Панкреатин",
        "manufacturer": "Abbott",
        "form": "капсулы",
        "atx": "A09AA02",
        "dispensing": "otc",
        "storage": "normal",
        "category": "ЖКТ",
        "variants": [("10000 ЕД", "№20", "76.00"), ("25000 ЕД", "№20", "145.00")],
    },
    {
        "brand": "Смекта",
        "inn": "Смектит диоктаэдрический",
        "manufacturer": "Ipsen",
        "form": "порошок",
        "atx": "A07BC05",
        "dispensing": "otc",
        "storage": "normal",
        "category": "ЖКТ",
        "variants": [("3 г", "№10", "32.00")],
    },
    {
        "brand": "Активированный уголь",
        "inn": "Уголь активированный",
        "manufacturer": "Фармстандарт",
        "form": "таблетки",
        "atx": "A07BA01",
        "dispensing": "otc",
        "storage": "normal",
        "category": "ЖКТ",
        "variants": [("250 мг", "№10", "2.00")],
    },
    {
        "brand": "Лоперамид",
        "inn": "Лоперамид",
        "manufacturer": "Озон",
        "form": "капсулы",
        "atx": "A07DA03",
        "dispensing": "otc",
        "storage": "normal",
        "category": "ЖКТ",
        "variants": [("2 мг", "№20", "8.50")],
    },
    {
        "brand": "Дюфалак",
        "inn": "Лактулоза",
        "manufacturer": "Abbott",
        "form": "сироп",
        "atx": "A06AD11",
        "dispensing": "otc",
        "storage": "normal",
        "category": "ЖКТ",
        "variants": [("667 мг/мл 200 мл", "флакон", "64.00")],
    },
    {
        "brand": "Эспумизан",
        "inn": "Симетикон",
        "manufacturer": "Berlin-Chemie",
        "form": "капсулы",
        "atx": "A03AX13",
        "dispensing": "otc",
        "storage": "normal",
        "category": "ЖКТ",
        "variants": [("40 мг", "№25", "42.00")],
    },
    {
        "brand": "Ренни",
        "inn": "Кальция/магния карбонат",
        "manufacturer": "Bayer",
        "form": "таблетки жевательные",
        "atx": "A02AX",
        "dispensing": "otc",
        "storage": "normal",
        "category": "ЖКТ",
        "variants": [("№24", "№24", "37.00")],
    },
    # ── Антибиотики ───────────────────────────────────────────────────────
    {
        "brand": "Амоксициллин",
        "inn": "Амоксициллин",
        "manufacturer": "Sandoz",
        "form": "капсулы",
        "atx": "J01CA04",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Антибиотики",
        "variants": [("500 мг", "№20", "26.00"), ("250 мг", "№20", "18.00")],
    },
    {
        "brand": "Амоксиклав",
        "inn": "Амоксициллин+Клавуланат",
        "manufacturer": "Sandoz",
        "form": "таблетки покрытые",
        "atx": "J01CR02",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Антибиотики",
        "variants": [("875+125 мг", "№14", "78.00"), ("500+125 мг", "№15", "62.00")],
    },
    {
        "brand": "Аугментин",
        "inn": "Амоксициллин+Клавуланат",
        "manufacturer": "GlaxoSmithKline",
        "form": "порошок для суспензии",
        "atx": "J01CR02",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Антибиотики",
        "variants": [("400+57 мг/5 мл", "флакон", "69.00")],
    },
    {
        "brand": "Азитромицин",
        "inn": "Азитромицин",
        "manufacturer": "Озон",
        "form": "капсулы",
        "atx": "J01FA10",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Антибиотики",
        "variants": [("500 мг", "№3", "34.00")],
    },
    {
        "brand": "Сумамед",
        "inn": "Азитромицин",
        "manufacturer": "Pliva (Teva)",
        "form": "таблетки покрытые",
        "atx": "J01FA10",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Антибиотики",
        "variants": [("500 мг", "№3", "92.00")],
    },
    {
        "brand": "Цефтриаксон",
        "inn": "Цефтриаксон",
        "manufacturer": "Биосинтез",
        "form": "порошок для инъекций",
        "atx": "J01DD04",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Антибиотики",
        "variants": [("1 г", "флакон", "11.00")],
    },
    {
        "brand": "Ципрофлоксацин",
        "inn": "Ципрофлоксацин",
        "manufacturer": "Hemofarm",
        "form": "таблетки покрытые",
        "atx": "J01MA02",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Антибиотики",
        "variants": [("500 мг", "№10", "24.00")],
    },
    {
        "brand": "Супракс",
        "inn": "Цефиксим",
        "manufacturer": "Astellas",
        "form": "капсулы",
        "atx": "J01DD08",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Антибиотики",
        "variants": [("400 мг", "№6", "118.00")],
    },
    {
        "brand": "Метронидазол",
        "inn": "Метронидазол",
        "manufacturer": "Озон",
        "form": "таблетки",
        "atx": "J01XD01",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Антибиотики",
        "variants": [("250 мг", "№20", "8.00")],
    },
    # ── Простуда и ОРВИ ───────────────────────────────────────────────────
    {
        "brand": "Терафлю",
        "inn": "Комбинация",
        "manufacturer": "GlaxoSmithKline",
        "form": "порошок",
        "atx": "N02BE51",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Простуда и ОРВИ",
        "variants": [("№10", "№10", "58.00")],
    },
    {
        "brand": "Колдрекс",
        "inn": "Комбинация",
        "manufacturer": "GlaxoSmithKline",
        "form": "порошок",
        "atx": "N02BE51",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Простуда и ОРВИ",
        "variants": [("№10", "№10", "54.00")],
    },
    {
        "brand": "Ринза",
        "inn": "Комбинация",
        "manufacturer": "Unique",
        "form": "таблетки",
        "atx": "N02BE51",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Простуда и ОРВИ",
        "variants": [("№10", "№10", "26.00")],
    },
    {
        "brand": "Ксилометазолин",
        "inn": "Ксилометазолин",
        "manufacturer": "Фармстандарт",
        "form": "спрей назальный",
        "atx": "R01AA07",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Простуда и ОРВИ",
        "variants": [("0,1% 10 мл", "флакон", "14.00")],
    },
    {
        "brand": "Тизин",
        "inn": "Ксилометазолин",
        "manufacturer": "Johnson & Johnson",
        "form": "спрей назальный",
        "atx": "R01AA07",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Простуда и ОРВИ",
        "variants": [("0,1% 10 мл", "флакон", "38.00")],
    },
    {
        "brand": "Лазолван",
        "inn": "Амброксол",
        "manufacturer": "Sanofi",
        "form": "сироп",
        "atx": "R05CB06",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Простуда и ОРВИ",
        "variants": [("15 мг/5 мл 100 мл", "флакон", "52.00")],
    },
    {
        "brand": "АЦЦ",
        "inn": "Ацетилцистеин",
        "manufacturer": "Sandoz",
        "form": "таблетки шипучие",
        "atx": "R05CB01",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Простуда и ОРВИ",
        "variants": [("200 мг", "№20", "64.00"), ("600 мг", "№10", "72.00")],
    },
    {
        "brand": "Граммидин",
        "inn": "Грамицидин С",
        "manufacturer": "Валента",
        "form": "таблетки для рассасывания",
        "atx": "R02AB30",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Простуда и ОРВИ",
        "variants": [("№18", "№18", "46.00")],
    },
    {
        "brand": "Стрепсилс",
        "inn": "Комбинация",
        "manufacturer": "Reckitt Benckiser",
        "form": "таблетки для рассасывания",
        "atx": "R02AA20",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Простуда и ОРВИ",
        "variants": [("№24", "№24", "44.00")],
    },
    # ── Аллергия ──────────────────────────────────────────────────────────
    {
        "brand": "Супрастин",
        "inn": "Хлоропирамин",
        "manufacturer": "Egis",
        "form": "таблетки",
        "atx": "R06AC03",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Аллергия",
        "variants": [("25 мг", "№20", "32.00")],
    },
    {
        "brand": "Цетрин",
        "inn": "Цетиризин",
        "manufacturer": "Dr. Reddy's",
        "form": "таблетки покрытые",
        "atx": "R06AE07",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Аллергия",
        "variants": [("10 мг", "№20", "36.00")],
    },
    {
        "brand": "Зодак",
        "inn": "Цетиризин",
        "manufacturer": "Zentiva",
        "form": "капли",
        "atx": "R06AE07",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Аллергия",
        "variants": [("10 мг/мл 20 мл", "флакон", "48.00")],
    },
    {
        "brand": "Лоратадин",
        "inn": "Лоратадин",
        "manufacturer": "Озон",
        "form": "таблетки",
        "atx": "R06AX13",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Аллергия",
        "variants": [("10 мг", "№10", "11.00")],
    },
    {
        "brand": "Эриус",
        "inn": "Дезлоратадин",
        "manufacturer": "Bayer",
        "form": "таблетки покрытые",
        "atx": "R06AX27",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Аллергия",
        "variants": [("5 мг", "№10", "62.00")],
    },
    # ── Сердечно-сосудистые ───────────────────────────────────────────────
    {
        "brand": "Эналаприл",
        "inn": "Эналаприл",
        "manufacturer": "Hemofarm",
        "form": "таблетки",
        "atx": "C09AA02",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Сердечно-сосудистые",
        "variants": [("10 мг", "№20", "9.00"), ("20 мг", "№20", "13.00")],
    },
    {
        "brand": "Лизиноприл",
        "inn": "Лизиноприл",
        "manufacturer": "Sandoz",
        "form": "таблетки",
        "atx": "C09AA03",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Сердечно-сосудистые",
        "variants": [("10 мг", "№30", "24.00")],
    },
    {
        "brand": "Конкор",
        "inn": "Бисопролол",
        "manufacturer": "Merck",
        "form": "таблетки покрытые",
        "atx": "C07AB07",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Сердечно-сосудистые",
        "variants": [("5 мг", "№30", "58.00"), ("10 мг", "№30", "78.00")],
    },
    {
        "brand": "Амлодипин",
        "inn": "Амлодипин",
        "manufacturer": "Озон",
        "form": "таблетки",
        "atx": "C08CA01",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Сердечно-сосудистые",
        "variants": [("5 мг", "№30", "16.00")],
    },
    {
        "brand": "Лозап",
        "inn": "Лозартан",
        "manufacturer": "Zentiva",
        "form": "таблетки покрытые",
        "atx": "C09CA01",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Сердечно-сосудистые",
        "variants": [("50 мг", "№30", "54.00")],
    },
    {
        "brand": "Кардиомагнил",
        "inn": "Ацетилсалициловая кислота",
        "manufacturer": "Takeda",
        "form": "таблетки покрытые",
        "atx": "B01AC06",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Сердечно-сосудистые",
        "variants": [("75 мг", "№100", "68.00")],
    },
    {
        "brand": "Аторвастатин",
        "inn": "Аторвастатин",
        "manufacturer": "Teva",
        "form": "таблетки покрытые",
        "atx": "C10AA05",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Сердечно-сосудистые",
        "variants": [("20 мг", "№30", "44.00")],
    },
    {
        "brand": "Валидол",
        "inn": "Левоментол",
        "manufacturer": "Фармстандарт",
        "form": "таблетки",
        "atx": "C01EX",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Сердечно-сосудистые",
        "variants": [("60 мг", "№10", "3.80")],
    },
    {
        "brand": "Корвалол",
        "inn": "Комбинация",
        "manufacturer": "Фармстандарт",
        "form": "капли",
        "atx": "N05CB02",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Сердечно-сосудистые",
        "variants": [("25 мл", "флакон", "12.00")],
    },
    # ── Неврология ────────────────────────────────────────────────────────
    {
        "brand": "Глицин",
        "inn": "Глицин",
        "manufacturer": "Биотики",
        "form": "таблетки подъязычные",
        "atx": "N06BX",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Неврология",
        "variants": [("100 мг", "№50", "26.00")],
    },
    {
        "brand": "Мексидол",
        "inn": "Этилметилгидроксипиридина сукцинат",
        "manufacturer": "Фармасофт",
        "form": "таблетки покрытые",
        "atx": "N07XX",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Неврология",
        "variants": [("125 мг", "№30", "94.00")],
    },
    {
        "brand": "Афобазол",
        "inn": "Фабомотизол",
        "manufacturer": "Фармстандарт",
        "form": "таблетки",
        "atx": "N05BX",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Неврология",
        "variants": [("10 мг", "№60", "84.00")],
    },
    {
        "brand": "Новопассит",
        "inn": "Комбинация",
        "manufacturer": "Teva",
        "form": "раствор",
        "atx": "N05CM",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Неврология",
        "variants": [("100 мл", "флакон", "72.00")],
    },
    # ── Витамины и БАД ────────────────────────────────────────────────────
    {
        "brand": "Аскорбиновая кислота",
        "inn": "Аскорбиновая кислота",
        "manufacturer": "Фармстандарт",
        "form": "драже",
        "atx": "A11GA01",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Витамины и БАД",
        "variants": [("50 мг", "№200", "18.00")],
    },
    {
        "brand": "Ревит",
        "inn": "Поливитамины",
        "manufacturer": "Алтайвитамины",
        "form": "драже",
        "atx": "A11AA",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Витамины и БАД",
        "variants": [("№100", "№100", "14.00")],
    },
    {
        "brand": "Компливит",
        "inn": "Поливитамины",
        "manufacturer": "Фармстандарт",
        "form": "таблетки покрытые",
        "atx": "A11AA",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Витамины и БАД",
        "variants": [("№60", "№60", "78.00")],
    },
    {
        "brand": "Аквадетрим",
        "inn": "Колекальциферол (вит. D3)",
        "manufacturer": "Acino",
        "form": "капли",
        "atx": "A11CC01",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Витамины и БАД",
        "variants": [("15000 МЕ/мл 10 мл", "флакон", "62.00")],
    },
    {
        "brand": "Магне B6",
        "inn": "Магния лактат+Пиридоксин",
        "manufacturer": "Sanofi",
        "form": "таблетки покрытые",
        "atx": "A12CC",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Витамины и БАД",
        "variants": [("№50", "№50", "98.00")],
    },
    {
        "brand": "Супрадин",
        "inn": "Поливитамины",
        "manufacturer": "Bayer",
        "form": "таблетки шипучие",
        "atx": "A11AA",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Витамины и БАД",
        "variants": [("№10", "№10", "86.00")],
    },
    {
        "brand": "Омега-3",
        "inn": "Омега-3 кислоты",
        "manufacturer": "Solgar",
        "form": "капсулы",
        "atx": "C10AX",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Витамины и БАД",
        "variants": [("950 мг", "№60", "168.00")],
    },
    # ── Антисептики и перевязка ───────────────────────────────────────────
    {
        "brand": "Хлоргексидин",
        "inn": "Хлоргексидин",
        "manufacturer": "Южфарм",
        "form": "раствор",
        "atx": "D08AC02",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Антисептики и перевязка",
        "variants": [("0,05% 100 мл", "флакон", "5.50")],
    },
    {
        "brand": "Перекись водорода",
        "inn": "Водорода пероксид",
        "manufacturer": "Самарамедпром",
        "form": "раствор",
        "atx": "D08AX01",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Антисептики и перевязка",
        "variants": [("3% 100 мл", "флакон", "4.50")],
    },
    {
        "brand": "Йод",
        "inn": "Йод",
        "manufacturer": "Тульская ФФ",
        "form": "раствор спиртовой",
        "atx": "D08AG03",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Антисептики и перевязка",
        "variants": [("5% 25 мл", "флакон", "4.00")],
    },
    {
        "brand": "Зеленка",
        "inn": "Бриллиантовый зелёный",
        "manufacturer": "Тульская ФФ",
        "form": "раствор спиртовой",
        "atx": "D08AX",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Антисептики и перевязка",
        "variants": [("1% 25 мл", "флакон", "4.00")],
    },
    {
        "brand": "Бинт марлевый",
        "inn": "—",
        "manufacturer": "Навтекс",
        "form": "бинт",
        "atx": "—",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Антисептики и перевязка",
        "variants": [("5 м х 10 см", "шт", "3.50")],
    },
    {
        "brand": "Вата хлопковая",
        "inn": "—",
        "manufacturer": "Навтекс",
        "form": "вата",
        "atx": "—",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Антисептики и перевязка",
        "variants": [("100 г", "уп", "9.00")],
    },
    {
        "brand": "Пластырь бактерицидный",
        "inn": "—",
        "manufacturer": "Verro",
        "form": "пластырь",
        "atx": "—",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Антисептики и перевязка",
        "variants": [("№20", "№20", "12.00")],
    },
    # ── Дерматология ──────────────────────────────────────────────────────
    {
        "brand": "Левомеколь",
        "inn": "Хлорамфеникол+Метилурацил",
        "manufacturer": "Нижфарм",
        "form": "мазь",
        "atx": "D06C",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Дерматология",
        "variants": [("40 г", "туба", "18.00")],
    },
    {
        "brand": "Акридерм",
        "inn": "Бетаметазон",
        "manufacturer": "Акрихин",
        "form": "крем",
        "atx": "D07AC01",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Дерматология",
        "variants": [("0,05% 15 г", "туба", "34.00")],
    },
    {
        "brand": "Бепантен",
        "inn": "Декспантенол",
        "manufacturer": "Bayer",
        "form": "крем",
        "atx": "D03AX03",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Дерматология",
        "variants": [("5% 30 г", "туба", "78.00")],
    },
    {
        "brand": "Тербинафин",
        "inn": "Тербинафин",
        "manufacturer": "Озон",
        "form": "крем",
        "atx": "D01AE15",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Дерматология",
        "variants": [("1% 15 г", "туба", "42.00")],
    },
    # ── Офтальмология ─────────────────────────────────────────────────────
    {
        "brand": "Альбуцид",
        "inn": "Сульфацетамид",
        "manufacturer": "Синтез",
        "form": "капли глазные",
        "atx": "S01AB04",
        "dispensing": "otc",
        "storage": "cold",
        "category": "Офтальмология",
        "variants": [("20% 10 мл", "флакон", "16.00")],
    },
    {
        "brand": "Тауфон",
        "inn": "Таурин",
        "manufacturer": "Московский ЭЗ",
        "form": "капли глазные",
        "atx": "S01XA",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Офтальмология",
        "variants": [("4% 10 мл", "флакон", "24.00")],
    },
    {
        "brand": "Визин",
        "inn": "Тетризолин",
        "manufacturer": "Johnson & Johnson",
        "form": "капли глазные",
        "atx": "S01GA02",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Офтальмология",
        "variants": [("0,05% 15 мл", "флакон", "82.00")],
    },
    # ── Гормональные / эндокринология (холодовая цепь) ────────────────────
    {
        "brand": "Инсулин Актрапид",
        "inn": "Инсулин человеческий",
        "manufacturer": "Novo Nordisk",
        "form": "раствор для инъекций",
        "atx": "A10AB01",
        "dispensing": "prescription",
        "storage": "cold",
        "category": "Эндокринология",
        "variants": [("100 МЕ/мл 10 мл", "флакон", "92.00")],
    },
    {
        "brand": "Метформин",
        "inn": "Метформин",
        "manufacturer": "Gedeon Richter",
        "form": "таблетки покрытые",
        "atx": "A10BA02",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Эндокринология",
        "variants": [("500 мг", "№60", "34.00"), ("1000 мг", "№60", "52.00")],
    },
    {
        "brand": "L-Тироксин",
        "inn": "Левотироксин натрия",
        "manufacturer": "Berlin-Chemie",
        "form": "таблетки",
        "atx": "H03AA01",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Эндокринология",
        "variants": [("50 мкг", "№50", "38.00"), ("100 мкг", "№50", "44.00")],
    },
    # ── Гинекология / урология ────────────────────────────────────────────
    {
        "brand": "Тержинан",
        "inn": "Комбинация",
        "manufacturer": "Bouchara-Recordati",
        "form": "таблетки вагинальные",
        "atx": "G01AA51",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Гинекология",
        "variants": [("№10", "№10", "118.00")],
    },
    {
        "brand": "Канефрон Н",
        "inn": "Комбинация растительная",
        "manufacturer": "Bionorica",
        "form": "драже",
        "atx": "G04BX",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Урология",
        "variants": [("№60", "№60", "128.00")],
    },
    {
        "brand": "Монурал",
        "inn": "Фосфомицин",
        "manufacturer": "Zambon",
        "form": "гранулы",
        "atx": "J01XX01",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Урология",
        "variants": [("3 г", "пакет", "96.00")],
    },
    # ── Расширение ассортимента ───────────────────────────────────────────
    {
        "brand": "Спазмалгон",
        "inn": "Комбинация",
        "manufacturer": "Sopharma",
        "form": "таблетки",
        "atx": "A03DA02",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Анальгетики и НПВС",
        "variants": [("№20", "№20", "36.00")],
    },
    {
        "brand": "Темпалгин",
        "inn": "Комбинация",
        "manufacturer": "Sopharma",
        "form": "таблетки покрытые",
        "atx": "N02BB52",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Анальгетики и НПВС",
        "variants": [("№20", "№20", "31.00")],
    },
    {
        "brand": "Мовалис",
        "inn": "Мелоксикам",
        "manufacturer": "Boehringer Ingelheim",
        "form": "таблетки",
        "atx": "M01AC06",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Анальгетики и НПВС",
        "variants": [("15 мг", "№20", "88.00")],
    },
    {
        "brand": "Аркоксиа",
        "inn": "Эторикоксиб",
        "manufacturer": "Merck",
        "form": "таблетки покрытые",
        "atx": "M01AH05",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Анальгетики и НПВС",
        "variants": [("90 мг", "№7", "96.00")],
    },
    {
        "brand": "Флемоксин Солютаб",
        "inn": "Амоксициллин",
        "manufacturer": "Astellas",
        "form": "таблетки диспергируемые",
        "atx": "J01CA04",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Антибиотики",
        "variants": [("500 мг", "№20", "64.00"), ("250 мг", "№20", "44.00")],
    },
    {
        "brand": "Кларитромицин",
        "inn": "Кларитромицин",
        "manufacturer": "Teva",
        "form": "таблетки покрытые",
        "atx": "J01FA09",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Антибиотики",
        "variants": [("500 мг", "№14", "58.00")],
    },
    {
        "brand": "Доксициклин",
        "inn": "Доксициклин",
        "manufacturer": "Озон",
        "form": "капсулы",
        "atx": "J01AA02",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Антибиотики",
        "variants": [("100 мг", "№10", "9.00")],
    },
    {
        "brand": "Левофлоксацин",
        "inn": "Левофлоксацин",
        "manufacturer": "Teva",
        "form": "таблетки покрытые",
        "atx": "J01MA12",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Антибиотики",
        "variants": [("500 мг", "№10", "62.00")],
    },
    {
        "brand": "Флуконазол",
        "inn": "Флуконазол",
        "manufacturer": "Озон",
        "form": "капсулы",
        "atx": "J02AC01",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Антибиотики",
        "variants": [("150 мг", "№1", "12.00")],
    },
    {
        "brand": "Фосфалюгель",
        "inn": "Алюминия фосфат",
        "manufacturer": "Astellas",
        "form": "гель",
        "atx": "A02AB03",
        "dispensing": "otc",
        "storage": "normal",
        "category": "ЖКТ",
        "variants": [("16 г", "№20", "78.00")],
    },
    {
        "brand": "Альмагель",
        "inn": "Комбинация",
        "manufacturer": "Teva",
        "form": "суспензия",
        "atx": "A02AD01",
        "dispensing": "otc",
        "storage": "normal",
        "category": "ЖКТ",
        "variants": [("170 мл", "флакон", "44.00")],
    },
    {
        "brand": "Урсосан",
        "inn": "Урсодезоксихолевая кислота",
        "manufacturer": "PRO.MED",
        "form": "капсулы",
        "atx": "A05AA02",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "ЖКТ",
        "variants": [("250 мг", "№50", "168.00")],
    },
    {
        "brand": "Линекс",
        "inn": "Пробиотик",
        "manufacturer": "Sandoz",
        "form": "капсулы",
        "atx": "A07FA51",
        "dispensing": "otc",
        "storage": "normal",
        "category": "ЖКТ",
        "variants": [("№16", "№16", "62.00"), ("№32", "№32", "108.00")],
    },
    {
        "brand": "Хилак форте",
        "inn": "Комбинация",
        "manufacturer": "Teva",
        "form": "капли",
        "atx": "A07FA",
        "dispensing": "otc",
        "storage": "normal",
        "category": "ЖКТ",
        "variants": [("30 мл", "флакон", "72.00")],
    },
    {
        "brand": "Энтерофурил",
        "inn": "Нифуроксазид",
        "manufacturer": "Bosnalijek",
        "form": "капсулы",
        "atx": "A07AX03",
        "dispensing": "otc",
        "storage": "normal",
        "category": "ЖКТ",
        "variants": [("200 мг", "№16", "54.00")],
    },
    {
        "brand": "Регидрон",
        "inn": "Комбинация солей",
        "manufacturer": "Orion",
        "form": "порошок",
        "atx": "A07CA",
        "dispensing": "otc",
        "storage": "normal",
        "category": "ЖКТ",
        "variants": [("№20", "№20", "98.00")],
    },
    {
        "brand": "Синупрет",
        "inn": "Комбинация растительная",
        "manufacturer": "Bionorica",
        "form": "драже",
        "atx": "R05X",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Простуда и ОРВИ",
        "variants": [("№50", "№50", "92.00")],
    },
    {
        "brand": "Мукалтин",
        "inn": "Алтея экстракт",
        "manufacturer": "Фармстандарт",
        "form": "таблетки",
        "atx": "R05CA",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Простуда и ОРВИ",
        "variants": [("50 мг", "№10", "3.00")],
    },
    {
        "brand": "Бромгексин",
        "inn": "Бромгексин",
        "manufacturer": "Берёзовский ФЗ",
        "form": "таблетки",
        "atx": "R05CB02",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Простуда и ОРВИ",
        "variants": [("8 мг", "№50", "16.00")],
    },
    {
        "brand": "Арбидол",
        "inn": "Умифеновир",
        "manufacturer": "Фармстандарт",
        "form": "капсулы",
        "atx": "J05AX13",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Простуда и ОРВИ",
        "variants": [("100 мг", "№20", "78.00")],
    },
    {
        "brand": "Каметон",
        "inn": "Комбинация",
        "manufacturer": "Виалайн",
        "form": "аэрозоль",
        "atx": "R02AA",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Простуда и ОРВИ",
        "variants": [("30 г", "баллон", "26.00")],
    },
    {
        "brand": "Тавегил",
        "inn": "Клемастин",
        "manufacturer": "Novartis",
        "form": "таблетки",
        "atx": "R06AA04",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Аллергия",
        "variants": [("1 мг", "№20", "34.00")],
    },
    {
        "brand": "Фенистил",
        "inn": "Диметинден",
        "manufacturer": "GlaxoSmithKline",
        "form": "капли",
        "atx": "R06AB03",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Аллергия",
        "variants": [("1 мг/мл 20 мл", "флакон", "58.00")],
    },
    {
        "brand": "Нитроглицерин",
        "inn": "Нитроглицерин",
        "manufacturer": "Фармстандарт",
        "form": "таблетки подъязычные",
        "atx": "C01DA02",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Сердечно-сосудистые",
        "variants": [("0,5 мг", "№40", "8.00")],
    },
    {
        "brand": "Капотен",
        "inn": "Каптоприл",
        "manufacturer": "Акрихин",
        "form": "таблетки",
        "atx": "C09AA01",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Сердечно-сосудистые",
        "variants": [("25 мг", "№40", "44.00")],
    },
    {
        "brand": "ТромбоАсс",
        "inn": "Ацетилсалициловая кислота",
        "manufacturer": "G.L. Pharma",
        "form": "таблетки покрытые",
        "atx": "B01AC06",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Сердечно-сосудистые",
        "variants": [("100 мг", "№30", "34.00")],
    },
    {
        "brand": "Детралекс",
        "inn": "Диосмин+Гесперидин",
        "manufacturer": "Servier",
        "form": "таблетки покрытые",
        "atx": "C05CA53",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Сердечно-сосудистые",
        "variants": [("№30", "№30", "168.00")],
    },
    {
        "brand": "Фенибут",
        "inn": "Аминофенилмасляная кислота",
        "manufacturer": "Озон",
        "form": "таблетки",
        "atx": "N06BX",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Неврология",
        "variants": [("250 мг", "№20", "62.00")],
    },
    {
        "brand": "Актовегин",
        "inn": "Депротеинизированный гемодериват",
        "manufacturer": "Takeda",
        "form": "таблетки покрытые",
        "atx": "N06AX",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Неврология",
        "variants": [("200 мг", "№50", "212.00")],
    },
    {
        "brand": "Кальций-Д3 Никомед",
        "inn": "Кальций+Колекальциферол",
        "manufacturer": "Takeda",
        "form": "таблетки жевательные",
        "atx": "A12AX",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Витамины и БАД",
        "variants": [("№60", "№60", "112.00")],
    },
    {
        "brand": "Витрум",
        "inn": "Поливитамины",
        "manufacturer": "Unipharm",
        "form": "таблетки покрытые",
        "atx": "A11AA",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Витамины и БАД",
        "variants": [("№60", "№60", "186.00")],
    },
    {
        "brand": "Фолиевая кислота",
        "inn": "Фолиевая кислота",
        "manufacturer": "Озон",
        "form": "таблетки",
        "atx": "B03BB01",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Витамины и БАД",
        "variants": [("1 мг", "№50", "9.00")],
    },
    {
        "brand": "Гематоген",
        "inn": "Альбумин чёрный пищевой",
        "manufacturer": "Фармстандарт",
        "form": "плитка",
        "atx": "B03A",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Витамины и БАД",
        "variants": [("40 г", "шт", "6.00")],
    },
    {
        "brand": "Пантенол",
        "inn": "Декспантенол",
        "manufacturer": "Hemofarm",
        "form": "спрей",
        "atx": "D03AX03",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Дерматология",
        "variants": [("130 г", "баллон", "86.00")],
    },
    {
        "brand": "Цинковая мазь",
        "inn": "Цинка оксид",
        "manufacturer": "Тульская ФФ",
        "form": "мазь",
        "atx": "D02AB",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Дерматология",
        "variants": [("10% 25 г", "туба", "8.00")],
    },
    {
        "brand": "Клотримазол",
        "inn": "Клотримазол",
        "manufacturer": "Акрихин",
        "form": "крем",
        "atx": "D01AC01",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Дерматология",
        "variants": [("1% 20 г", "туба", "22.00")],
    },
    {
        "brand": "Мирамистин",
        "inn": "Бензилдиметил...аммоний хлорид",
        "manufacturer": "Инфамед",
        "form": "раствор",
        "atx": "D08AJ",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Антисептики и перевязка",
        "variants": [("0,01% 50 мл", "флакон", "78.00"), ("0,01% 150 мл", "флакон", "168.00")],
    },
    {
        "brand": "Нафтизин",
        "inn": "Нафазолин",
        "manufacturer": "Славянская аптека",
        "form": "капли назальные",
        "atx": "R01AA08",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Простуда и ОРВИ",
        "variants": [("0,1% 15 мл", "флакон", "5.00")],
    },
    {
        "brand": "Отипакс",
        "inn": "Феназон+Лидокаин",
        "manufacturer": "Biocodex",
        "form": "капли ушные",
        "atx": "S02DA30",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Простуда и ОРВИ",
        "variants": [("16 г", "флакон", "92.00")],
    },
    {
        "brand": "Цистон",
        "inn": "Комбинация растительная",
        "manufacturer": "Himalaya",
        "form": "таблетки",
        "atx": "G04",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Урология",
        "variants": [("№100", "№100", "138.00")],
    },
    {
        "brand": "Ливарол",
        "inn": "Кетоконазол",
        "manufacturer": "Нижфарм",
        "form": "суппозитории вагинальные",
        "atx": "G01AF11",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Гинекология",
        "variants": [("400 мг", "№5", "78.00")],
    },
    {
        "brand": "Парацетамол детский",
        "inn": "Парацетамол",
        "manufacturer": "Фармстандарт",
        "form": "сироп",
        "atx": "N02BE01",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Анальгетики и НПВС",
        "variants": [("120 мг/5 мл 100 мл", "флакон", "22.00")],
    },
    {
        "brand": "Нимесил",
        "inn": "Нимесулид",
        "manufacturer": "Berlin-Chemie",
        "form": "гранулы",
        "atx": "M01AX17",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Анальгетики и НПВС",
        "variants": [("100 мг", "№30", "118.00")],
    },
    {
        "brand": "Гастал",
        "inn": "Комбинация",
        "manufacturer": "Teva",
        "form": "таблетки для рассасывания",
        "atx": "A02AD",
        "dispensing": "otc",
        "storage": "normal",
        "category": "ЖКТ",
        "variants": [("№12", "№12", "34.00")],
    },
    {
        "brand": "Бифиформ",
        "inn": "Пробиотик",
        "manufacturer": "Ferrosan",
        "form": "капсулы",
        "atx": "A07FA",
        "dispensing": "otc",
        "storage": "normal",
        "category": "ЖКТ",
        "variants": [("№30", "№30", "118.00")],
    },
    {
        "brand": "Доктор Мом",
        "inn": "Комбинация растительная",
        "manufacturer": "Johnson & Johnson",
        "form": "пастилки",
        "atx": "R05X",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Простуда и ОРВИ",
        "variants": [("№20", "№20", "44.00")],
    },
    {
        "brand": "Верапамил",
        "inn": "Верапамил",
        "manufacturer": "Озон",
        "form": "таблетки покрытые",
        "atx": "C08DA01",
        "dispensing": "prescription",
        "storage": "normal",
        "category": "Сердечно-сосудистые",
        "variants": [("40 мг", "№50", "14.00")],
    },
    {
        "brand": "Аевит",
        "inn": "Витамины A+E",
        "manufacturer": "Алтайвитамины",
        "form": "капсулы",
        "atx": "A11JA",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Витамины и БАД",
        "variants": [("№30", "№30", "24.00")],
    },
    {
        "brand": "Серная мазь",
        "inn": "Сера осаждённая",
        "manufacturer": "Тульская ФФ",
        "form": "мазь",
        "atx": "D10AB",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Дерматология",
        "variants": [("33% 25 г", "туба", "12.00")],
    },
    {
        "brand": "Систейн Ультра",
        "inn": "Увлажняющий раствор",
        "manufacturer": "Alcon",
        "form": "капли глазные",
        "atx": "S01XA20",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Офтальмология",
        "variants": [("10 мл", "флакон", "188.00")],
    },
    {
        "brand": "Уролесан",
        "inn": "Комбинация растительная",
        "manufacturer": "Галичфарм",
        "form": "капли",
        "atx": "G04BX",
        "dispensing": "otc",
        "storage": "normal",
        "category": "Урология",
        "variants": [("25 мл", "флакон", "48.00")],
    },
]
